config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about' => 'home#about'
  get 'media'=> 'home#media'
  get 'contact' => 'home#contact'

  get 'repertoire' => 'repertoires#index'

  resources :repertoires
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repertoire.rb
class Repertoire < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def media
  end

  def contact
  end
end

app/controllers/repertoires_controller.rb
class RepertoiresController < ApplicationController
  before_action :set_repertoire, only: [:show, :edit, :update, :destroy]

  # GET /repertoires
  # GET /repertoires.json
  def index
    @repertoires = Repertoire.all
  end

  # GET /repertoires/1
  # GET /repertoires/1.json
  def show
  end

  # GET /repertoires/new
  def new
    @repertoire = Repertoire.new
  end

  # GET /repertoires/1/edit
  def edit
  end

  # POST /repertoires
  # POST /repertoires.json
  def create
    @repertoire = Repertoire.new(repertoire_params)

    respond_to do |format|
      if @repertoire.save
        format.html { redirect_to @repertoire, notice: 'Repertoire was successfully created.' }
        format.json { render :show, status: :created, location: @repertoire }
      else
        format.html { render :new }
        format.json { render json: @repertoire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repertoires/1
  # PATCH/PUT /repertoires/1.json
  def update
    respond_to do |format|
      if @repertoire.update(repertoire_params)
        format.html { redirect_to @repertoire, notice: 'Repertoire was successfully updated.' }
        format.json { render :show, status: :ok, location: @repertoire }
      else
        format.html { render :edit }
        format.json { render json: @repertoire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repertoires/1
  # DELETE /repertoires/1.json
  def destroy
    @repertoire.destroy
    respond_to do |format|
      format.html { redirect_to repertoires_url, notice: 'Repertoire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repertoire
      @repertoire = Repertoire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repertoire_params
      params.require(:repertoire).permit(:composer, :title, :date_performed, :ensemble_performed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repertoires_helper.rb
module RepertoiresHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/media.html.erb
<h1>Home#media</h1>
<p>Find me in app/views/home/media.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NathanLeaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repertoires/_form.html.erb
<%= form_with(model: repertoire, local: true) do |form| %>
  <% if repertoire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repertoire.errors.count, "error") %> prohibited this repertoire from being saved:</h2>

      <ul>
      <% repertoire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :composer %>
    <%= form.text_field :composer %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date_performed %>
    <%= form.date_select :date_performed %>
  </div>

  <div class="field">
    <%= form.label :ensemble_performed %>
    <%= form.text_field :ensemble_performed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repertoires/edit.html.erb
<h1>Editing Repertoire</h1>

<%= render 'form', repertoire: @repertoire %>

<%= link_to 'Show', @repertoire %> |
<%= link_to 'Back', repertoires_path %>

app/views/repertoires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repertoires</h1>

<table>
  <thead>
    <tr>
      <th>Composer</th>
      <th>Title</th>
      <th>Date performed</th>
      <th>Ensemble performed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repertoires.each do |repertoire| %>
      <tr>
        <td><%= repertoire.composer %></td>
        <td><%= repertoire.title %></td>
        <td><%= repertoire.date_performed %></td>
        <td><%= repertoire.ensemble_performed %></td>
        <td><%= link_to 'Show', repertoire %></td>
        <td><%= link_to 'Edit', edit_repertoire_path(repertoire) %></td>
        <td><%= link_to 'Destroy', repertoire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repertoire', new_repertoire_path %>

app/views/repertoires/new.html.erb
<h1>New Repertoire</h1>

<%= render 'form', repertoire: @repertoire %>

<%= link_to 'Back', repertoires_path %>

app/views/repertoires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Composer:</strong>
  <%= @repertoire.composer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @repertoire.title %>
</p>

<p>
  <strong>Date performed:</strong>
  <%= @repertoire.date_performed %>
</p>

<p>
  <strong>Ensemble performed:</strong>
  <%= @repertoire.ensemble_performed %>
</p>

<%= link_to 'Edit', edit_repertoire_path(@repertoire) %> |
<%= link_to 'Back', repertoires_path %>